version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project
    overwrite: true
hooks:
  BeforeInstall: 
    - location: clean_instance.sh
      timeout: 300
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
    - location: install_project_dependencies.sh
      timeout: 300
